Factory/Models/DesignTimeDbFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models
{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {

    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<EngineerMachine>{};
    }
    public int EngineerId { get; set; }
    public string Name { get; set; }
    
    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models
{
  public class EngineerMachine
  {
    public int EngineerMachineId { get; set; }
    public int MachineId { get; set; }
    public int EngineerId { get; set; }
    public virtual Machine Machine { get; set; }
    public virtual Engineer Engineer { get; set; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<EngineerMachine> EngineerMachine { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>{};
    }
    public int MachineId { get; set; }
    public string Hardware { get; set; }
    
    public virtual ICollection<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;
    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Engineer> model = _db.Engineers.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
        .Include(engineer => engineer.JoinEntities)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Factory.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;
    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Machines.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine, int EngineerId)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
        .Include(machine => machine.JoinEntities)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

<div id="push-page-content-up"></div>

@model Factory.Models.Engineer

<div class="container" id="main">
  <h1>Employ a new Zeta-Brute</h1>
  <p>"Boss! We have some applicants, but they need new code names. Would you do us the honors?"</p>

  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <input type="submit" value="Let's get them working">
  }
  <p>@Html.ActionLink("List of Engineers", "Index")</p>
</div>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

<div id="push-page-content-up"></div>

@model Factory.Models.Engineer;

<div class="container" id="main">
  <h1>Marked for Seperation</h1>

  <p>"Boss! We have a lot of work to get done!! I-I-I'm sorry... Would you like to let this worker go?"</p>

  <h3>@Html.DisplayNameFor(model => model.Name):</h3>
  <h4>@Html.DisplayFor(model => model.Name)</h4>

  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" />
  }

  <h3>@Html.ActionLink("List of Engineers", "Index")</h3>
</div>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

<div id="push-page-content-up"></div>

@model Factory.Models.Engineer;

<div class="container" id="main">
  <h1>Zeta-Brute Details</h1>
  <hr>

  <h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

  @if (@Model.JoinEntities.Count == 0)
  {
    <p><em>"This one is awaiting a job to get started on. What machine would you like to put them on?"</em></p>
  }
  else
  {
    <h4>@Html.DisplayFor(model => model.Name) has been assigned to these Machines:</h4>
    <ul>
      @foreach (var join in Model.JoinEntities)
      {
        <li>@join.Machine.Hardware</li>
      }
    </ul>
  }

  <h3>@Html.ActionLink("List of Engineers", "Index", "Engineers")</h3>
  <h3>@Html.ActionLink("Edit Engineer", "Edit", new { id = Model.EngineerId })</h3>
  <h3>@Html.ActionLink("Remove Engineer", "Delete", new { id = Model.EngineerId })</h3>
</div>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<div class="container" id="main">
  <h1>Modify this Engineer's Code Name</h1>

  <h4>Would would you like to call them: @Html.DisplayFor(model => model.Name)</h4>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.EngineerId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <input type="submit" value="Save" />
  }
  <p>@Html.ActionLink("List of Engineers", "Index")</p>
</div>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

<div id="push-page-content-up"></div>

@using Factory.Models;

<div class="container" id="main">
<h1>Zeta-String Engineers</h1>

<p>"Y-Your current Zeta-Brutes sir!"</p>

@if (@Model.Count == 0)
{
  <p><em>"I'm..I'm sorry to report sir! Looks like everyone bailed. We must hire more workers..."</em></p>
}

<ul>
  @foreach (Engineer engineer in Model)
  { 
    <li>@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId })</li>
  }
</ul>

<p><em>"We can add more workers if you would like? Riddler, Mad Hatter and Two-Face have agreed to help our efforts and have sent over some of their people."</em></p>

<h3>@Html.ActionLink("Employ an Engineer", "Create")</h3>
</div>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<div id="push-page-content-up"></div>
<div class="container" id="main">
  <h1>Welcome Back Mr. SillyStringz</h1>
  <p><em>Batman, or rather Bruce Wayne and his little "Wayne Enterprises" must be stopped!</em></p>
  <img src="~/img/batman.png" alt="the batman" width="150">
  <p><em>Give commands to your troops and assign them to production.</em></p>
  <h4>Engineers:</h4>
  <h5><strong>@Html.ActionLink("Zeta-String Engineers", "Index", "Engineers")</strong></h5>
  <h4>Machines:</h4>
  <h5><strong>@Html.ActionLink("Production Equipment", "Index", "Machines")</strong></h5>
</div>

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

<div id="push-page-content-up"></div>

@model Factory.Models.Machine;

<div class="container" id="main">
  <h1>Assign an Engineer to this Machine</h1>

  <p><em>"Hey Boss, would you like to put someone on this Machine? We have some new hires that might be good here."</em>
  </p>

  <h4>Put a Zeta-Brute on: @Html.DisplayFor(model => model.Hardware)</h4>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.MachineId)

    @Html.Label("Assign this Engineer?: ")
    @Html.DropDownList("EngineerId")

    <input type="submit" value="Add 'em?" />
  }

  <h3>@Html.ActionLink("Current Machine List", "Index")</h3>
</div>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

<div id="push-page-content-up"></div>

@model Factory.Models.Machine;

<div class="container" id="main">
  <h1>Order some new Equipment from Bane?</h1>

  @using (Html.BeginForm())
  {
    <h5>Name of the Machine: </h5>
    @Html.TextBoxFor(model => model.Hardware)

    <div>
      <br>
      <h5>@Html.Label("Which Brute is going to be working on this machine?")</h5>
      <div>
        @Html.DropDownList("EngineerId")
      </div>
    </div>
    <br>
    <input type="submit" value="Place the order" class="btn btn-success" />
  }

  <h3>@Html.ActionLink("Current Machine List", "Index")</h3>
</div>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

<div id="push-page-content-up"></div>

@model Factory.Models.Machine

<div class="container" id="main">
  <h1>Marked for Destruction</h1>

  <p>"Sir? Do you really want to g-g-g-get rid of this Equipment?"</p>

  <h3>@Html.DisplayNameFor(model => model.Hardware):</h3>
  <h4>@Html.DisplayFor(model => model.Hardware)</h4>
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" />
  }
  <h3>@Html.ActionLink("Current Machine List", "Index")</h3>
</div>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

<div id="push-page-content-up"></div>

@model Factory.Models.Machine;

<div class="container" id="main">
  <h1>Production Equipment</h1>
  <hr>

  <h3>@Html.DisplayNameFor(model => model.Hardware): @Html.DisplayFor(model => model.Hardware)</h3>

  @if (@Model.JoinEntities.Count == 0)
  {
    <p>"Boss! This new equipment is ready to be assigned to workers. Would you like to assign someone to get working?"</p>
  }
  else
  {
    <h4>"So far, these are the Zeta-Brutes who are working with this Equipment"</h4>
    <ul>
      @foreach (var join in Model.JoinEntities)
      {
        <li>@join.Engineer.Name</li>
        @using (Html.BeginForm("DeleteEngineer", "Machines"))
        {
          @Html.Hidden("joinId", @join.EngineerMachineId)
          <input type="submit" value="Delete" />
        }
      }
    </ul>
  }

  <h3>@Html.ActionLink("Assign an Engineer", "AddEngineer", new { id = Model.MachineId})</h3>
  <h3>@Html.ActionLink("Modify a Machine", "Edit", new { id = Model.MachineId})</h3>
  <h3>@Html.ActionLink("Remove a Machine from Factory", "Delete", new { id = Model.MachineId})</h3>
  <h3>@Html.ActionLink("Current Machine List", "Index")</h3>
</div>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="container" id="main">
  <h1>Modify this Machine?</h1>

  <h4>Edit this Equipment: @Html.DisplayFor(model => model.Hardware)</h4>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.MachineId)

    @Html.LabelFor(model => model.Hardware)
    @Html.EditorFor(model => model.Hardware)

    @Html.Label("Engineer asignment:")
    @Html.DropDownList("EngineerId")

    <input type="submit" value="Save" />
  }

  <p>@Html.ActionLink("Current Machine List", "Index")</p>
</div>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

<div id="push-page-content-up"></div>

@using Factory.Models;
@model List<Factory.Models.Machine>;

<div class="container" id="main">
<h1>Zeta-String Production Equipment</h1>

@if (Model.Count == 0)
{
  <p><em>"I-I am terribly sorry to report that our factory is b-b-b-BARREN! Joker must of sent his goons to steal what equipment we had!! We might have to create a new contract with Bane to secure more Equipment so we can begin production imediately. Y-Y-Your orders sir?"</em></p>
}
else
{
  <p><em>"G-Great news sir! Bane delivered as he agreed upon. The top secret tech Mr. Freeze was working on is now ours!"</em></p>
}

@foreach (Machine machine in Model)
{
  <li>@Html.ActionLink($"{machine.Hardware}", "Details", new { id = machine.MachineId })</li>
}
<br>
<h3>@Html.ActionLink("Add a new Machine", "Create")</h3>
</div>

Factory/Views/Shared/Header.cshtml
<header>
  <div class="container">
    <div class="row">
      <img src="~/img/symbol.jpg" alt="the batman" width="100" id="left">
      <div class="col">
        <h4><strong>@Html.ActionLink("Z-STRING HEADQUARTERS", "Index", "Home")</strong></h4>
      </div>
      <img src="~/img/symbol.jpg" alt="the batman" width="100" id="right">
    </div>
  </div>
</header>
<div id="push-page-content-up"></div>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Mr. Sillystringz's Factory: A Batman Side-Story</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css">
  </head>
  <body>
  @await Html.PartialAsync("Header")
  <div class="container">
    @RenderBody()
  </div>
  </body>
</html>